<a href="https://colab.research.google.com/github/happydinnertime/AI-learning/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
print(“pandas version: %s” % pd.__version__)
import matplotlib
print("matplotlib version: %s" % matplotlib.__version__)
import numpy as np
print("numpy version: %s" % np.__version__)
import sklearn
print("scikit-learn version: %s" % sklearn.__version__)

SyntaxError: ignored

In [0]:
import numpy as np

In [0]:
np1 = np.array([1, 2, 3])
np2 = np.array([3, 4, 5])

In [0]:
ar2=np.array([[0,3,5],[2,3,8]]) #幾個 '[]' 代表有幾個 維度 (dimention)

In [7]:
print(ar2)

[[0 3 5]
 [2 3 8]]


In [8]:
ar2.shape

(2, 3)

In [0]:
ar=np.array([2,34,6,8])

In [11]:
ar.dtype

dtype('int64')

In [0]:
ar=np.array([2,-1,6,3], dtype= float )

In [17]:
ar.dtype

dtype('float64')

In [0]:
ar1=np.array([2,34,6,8.88])

In [0]:
intar1=ar1.astype(int) #型態轉換

In [14]:
print(intar1)

[ 2 34  6  8]


In [18]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [21]:
x=np.array([np.arange(1,6),np.arange(10,15)]); 
x

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14]])

In [22]:
x.ravel()

array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14])

In [23]:
x.T

array([[ 1, 10],
       [ 2, 11],
       [ 3, 12],
       [ 4, 13],
       [ 5, 14]])

In [24]:
x.T.ravel()

array([ 1, 10,  2, 11,  3, 12,  4, 13,  5, 14])

In [25]:
y = np.arange(2,10)
y

array([2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
y[-2]

8

In [27]:
ar = np.array([[2,3,4],[9,8,7],[11,12,13]])
#ar
#ar[1,2]
#ar[2,:]
#ar[:,1]
#ar[2,-1] 

#前行後列，從 0 開始

array([[ 2,  3,  4],
       [ 9,  8,  7],
       [11, 12, 13]])

In [28]:
ar = range(1000)      #Python for loop
%timeit [ar[i]**3 for i in ar]

1000 loops, best of 3: 357 µs per loop


In [29]:
ar = np.arange(1000)  #Vectorization 向量化計算
%timeit ar**3    #100 times faster than the upper code(Pythin for loop) 

The slowest run took 51.73 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 3.49 µs per loop


In [30]:
%tensorflow_version 2.x

SyntaxError: ignored

In [0]:
x = 